---

- include: logins.yml
  when: "{{ smash_logins }}"
  tags: [smash, logins]

- include: sudo.yml
  when: "{{ smash_sudo }}"
  tags: [smash, sudo]

- include: mkhomedir.yml
  when: "{{ smash_mkhomedir }}"
  tags: [smash, sshd, pam]

- include: acls.yml
  when: "{{ smash_acls | length }}"
  tags: [smash, acls]

- include: nfs_home.yml
  when: "{{ smash_nfs }}"
  tags: [smash, nfs]
